# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GRADLE_CMD: ./gradlew --no-daemon

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
            
      - name: Build source
        run: ${GRADLE_CMD} build
      
      - name: Build docker image
        run: ${GRADLE_CMD} dockerBuild
      
      - run: docker login ${{ secrets.DOCKER_REPO }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push docker container and helm chart
        run: ${GRADLE_CMD} dockerPush
      
      - name: Report
        run: ${GRADLE_CMD} projectReport dependencyCheckAggregate jacocoTestReport
